name: Maven Package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy:deploy-file -DgroupId="gov.va.wss.framework" -DartifactId="wss-framework-cache" -Dversion=${{ github.event.head_commit.message }} -Dfile=./wss-framework-cache.jar -Durl=https://maven.pkg.github.com/timothy-baker2/private-maven-repo -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: 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
